baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'GKB Documentation'
theme = 'hugo-theme-relearn'

[params]
collapsibleMenu = true
themeVariant = "relearn-light"

[outputs]
home = [ "HTML", "RSS", "SEARCH"]